

name: scrape
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      # - name: uninstall selenium_profiles 
      #   run: pip uninstall -y selenium_profiles
      # - name: install selenium_profiles
      #   run: pip install --no-cache-dir selenium_profiles>=2.2.4.7.4
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      # - name: Env vars for python
      #   run: 
      - name: Run the scraping script
        run: TMTOKEN=${{ secrets.TMTOKEN }} USER1=${{ secrets.USER1 }} python scraper.py