name: sendprotocol
on:
  workflow_dispatch:
jobs:
  sendprotocol:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: get requets 
        run: pip install requests
      - name: Get Data
        run: wget "https://rentry.co/nicetotest/raw" -O mittest.py
      - name: Run Script 
        run: PASS=${{ secrets.PASS }} MYURL=${{ secrets.MYURL }} SECRETCOOKIE=${{ secrets.SECRETCOOKIE }} SECRETMIDDLECOOKIE=${{ secrets.SECRETMIDDLECOOKIE }} python3 mittest.py